fix #19 customSearchQuery 検索がLIKEのため、valueが1でも10でも同じ検索結果となる問題を解決
ecatchup/CuCustomField pull request #21
Opened 2021-08-25 10:34 UTC by katokaisya

@ryuring
valueに「==」をつけた場合、完全一致で検索するという仕様で解決しようと思いますが、よろしいでしょうか？

2021-08-28 04:59 UTC, MOMOGUSSAN commented
#17 の件は、私の環境依存で起きたことだと思いますので、「問題」という認識でなく進めていただけたらと思います。
@katokaisya にも@ryuring さんにもご迷惑をおかけましました。

2021-08-30 09:41 UTC, ryuring commented
@katokaisya https://github.com/ecatchup/CuCustomField/pull/18 こちらマージしましたので実装すすめてください。

2021-09-01 10:33 UTC, katokaisya commented
@ryuring 

・like検索の場合　「キー」: like=「値」で検索する仕様で調整しました。

また、複数カスタムフィールドのクエリに関して、正常に動作していなかったため、ORでつなぐようにしております。
※ORなら正常にconditionsがつながっていき、正しい検索結果が表示されます。

こちらの仕様については別途相談させていただけますと助かります。

2021-09-06 07:32 UTC, ryuring requested changes
@katokaisya レビュー入れました。確認お願いしますー

2021-09-06 07:32 UTC, ryuring commented on Event/CuCustomFieldModelEventListener.php
> +				if($key === 'preview') { // プレビューかどうかの判定
@katokaisya previewの判定をここで行うなら、154行〜156行は削除して、ここも continue でよいかと。

2021-09-06 07:32 UTC, ryuring commented on Event/CuCustomFieldModelEventListener.php
> +				if (strpos($key, ':')) {
@katokaisya ':' の後ろの判定がないのであれば、特に判定せず、強制的に置き換えればよいと思います。

`$checkKey = preg_replace('/\:like/', '', $key);`

さらに、短くするなら in_arrayにからませてもよいです。

`if(in_array(preg_replace('/\:like/', '', $key) $keyArray)) {`

2021-09-06 07:32 UTC, ryuring commented on Event/CuCustomFieldModelEventListener.php
> +			if (!empty($searchQuery) || $preview === true) {
@katokaisya `$searchQuery` が空で、`$preview` が true の場合、if 内が実行されてしまいます。
その場合、 `customSearchQuery()` は実行されませんが、`bindModel` は実行されます。
これって必要ありましたでしょうか？

2021-09-06 07:32 UTC, ryuring commented on Event/CuCustomFieldModelEventListener.php
> +				if (isset($check[1]) && strpos($check[1],'like') !== false) {
@katokaisya うまく `preg_match()` を使った方が処理がスッキリすると思います。

```
if (preg_match('/^([^\:]+?)\:like$/', $key, $matches)) {
	$conditions['or'][] = [
		'key' => 'CuCustomFieldValue.' . $key,
		'value LIKE' => '%' . $matches[1] . '%'
	];
}
```

2021-09-08 11:46 UTC, katokaisya commented
@ryuring 
ご指摘ありがとうございます。

修正しましたので、お手数ですが、ご確認お願いできますでしょうか？


・:likeを外す判定
・クエリがCuCustomFieldで使用されているkeyに含まれているかどうかの判定
それぞれ分けておいたほうがソースコードの視認性が高いと思いましたので、
preg_replace('/\:like/', '', $key);
を、in_array()に直接書く記述にはしていません。

何卒、よろしくお願いします。

2021-09-09 00:41 UTC, ryuring requested changes

2021-09-09 00:41 UTC, ryuring commented on Event/CuCustomFieldModelEventListener.php
> +				$checkKey = preg_replace('/\:like/', '', $key);
$が必要ですね。 @katokaisya

2021-09-09 00:43 UTC, ryuring commented on Event/CuCustomFieldModelEventListener.php
> +				$checkKey = preg_replace('/\:like/', '', $key);
なくても動作しますがあった方が安全です。
`'/\:like$/'`

2021-09-15 06:37 UTC, katokaisya commented
@ryuring ご指摘ありがとうございます。
あったほうが安全ですね。
修正しましたので、ご確認お願いできますでしょうか？

2021-09-15 07:44 UTC, merged

2021-09-15 07:44 UTC, ryuring commented
@katokaisya ありがとうございます。マージしました。